default:
  username: admin
  password: NokiaSrl1!
fabrics:
  - site: S1
    id: 1000
    pool:
      loopbacks: 10.1.0.0/24
      links: 10.1.10.0/24
    spines:
      - name: S-S1-SP-CLI-01
        address: "172.100.100.11"
      - name: S-S1-SP-CLI-02
        address: "172.100.100.12"
    lifs:
      - id: 101
        name: S-S1-LF-CLI-0101
        address: "172.100.100.101"
      - id: 102
        name: S-S1-LF-CLI-0102
        address: "172.100.100.102"
    ports:
      - { sw: 101, if: 1, tpl: ESXi, desc: ESX1 }
      - { sw: [101, 102], if: 2, tpl: ESXi, desc: ESXi2 }
      - { sw: 102, if: 2, tpl: ESXi, desc: Err }
  - site: S2
    id: 2000
    pool:
      loopbacks: 10.2.0.0/24
      links: 10.2.10.0/24
    spines:
      - name: S-S2-SP-CLI-01
        address: "172.100.100.21"
      - name: S-S2-SP-CLI-02
        address: "172.100.100.22"
    lifs:
      - id: 201
        name: S-S2-LF-CLI-0101
        address: "172.100.100.201"
      - id: 202
        name: S-S2-LF-CLI-0102
        address: "172.100.100.202"
clients:
  client1:
    id: 666
    networks:
      Lan1:
        vlan_id: 42
        subnet: 192.168.1.1/24
templates:
  - name: ESXi
    type: esx
    clients:
      - client1
