default:
  username: admin
  password: NokiaSrl1!
fabrics:
  - site: S1
    pool:
      loopbacks: 10.1.0.0/24
      links: 10.1.10.0/24
    spines:
      - name: S-S1-SP-CLI-01
        address: "172.100.100.10"
      - name: S-S1-SP-CLI-02
        address: "172.100.100.11"
    lifs:
      - name: S-S1-LF-CLI-0101
        address: "172.100.100.101"
      - name: S-S1-LF-CLI-0102
        address: "172.100.100.102"
  - site: S2
    pool:
      loopbacks: 10.2.0.0/24
      links: 10.2.10.0/24
    spines:
      - name: S-S2-SP-CLI-01
        address: "172.100.100.21"
      - name: S-S2-SP-CLI-02
        address: "172.100.100.22"
    lifs:
      - name: S-S2-LF-CLI-0101
        address: "172.100.100.201"
      - name: S-S2-LF-CLI-0102
        address: "172.100.100.202"
